/// 전 세계 국가 목록 (ISO 3166-1 alpha-2 기준, 영문 A-Z 순서)
enum Country {
  afghanistan('AF', '아프가니스탄', 'Afghanistan', '🇦🇫'),
  albania('AL', '알바니아', 'Albania', '🇦🇱'),
  algeria('DZ', '알제리', 'Algeria', '🇩🇿'),
  andorra('AD', '안도라', 'Andorra', '🇦🇩'),
  angola('AO', '앙골라', 'Angola', '🇦🇴'),
  antiguaAndBarbuda('AG', '앤티가 바부다', 'Antigua and Barbuda', '🇦🇬'),
  argentina('AR', '아르헨티나', 'Argentina', '🇦🇷'),
  armenia('AM', '아르메니아', 'Armenia', '🇦🇲'),
  australia('AU', '호주', 'Australia', '🇦🇺'),
  austria('AT', '오스트리아', 'Austria', '🇦🇹'),
  azerbaijan('AZ', '아제르바이잔', 'Azerbaijan', '🇦🇿'),
  bahamas('BS', '바하마', 'Bahamas', '🇧🇸'),
  bahrain('BH', '바레인', 'Bahrain', '🇧🇭'),
  bangladesh('BD', '방글라데시', 'Bangladesh', '🇧🇩'),
  barbados('BB', '바베이도스', 'Barbados', '🇧🇧'),
  belarus('BY', '벨라루스', 'Belarus', '🇧🇾'),
  belgium('BE', '벨기에', 'Belgium', '🇧🇪'),
  belize('BZ', '벨리즈', 'Belize', '🇧🇿'),
  benin('BJ', '베냉', 'Benin', '🇧🇯'),
  bhutan('BT', '부탄', 'Bhutan', '🇧🇹'),
  bolivia('BO', '볼리비아', 'Bolivia', '🇧🇴'),
  bosniaAndHerzegovina('BA', '보스니아 헤르체고비나', 'Bosnia and Herzegovina', '🇧🇦'),
  botswana('BW', '보츠와나', 'Botswana', '🇧🇼'),
  brazil('BR', '브라질', 'Brazil', '🇧🇷'),
  brunei('BN', '브루나이', 'Brunei', '🇧🇳'),
  bulgaria('BG', '불가리아', 'Bulgaria', '🇧🇬'),
  burkinaFaso('BF', '부르키나파소', 'Burkina Faso', '🇧🇫'),
  burundi('BI', '부룬디', 'Burundi', '🇧🇮'),
  cambodia('KH', '캄보디아', 'Cambodia', '🇰🇭'),
  cameroon('CM', '카메룬', 'Cameroon', '🇨🇲'),
  canada('CA', '캐나다', 'Canada', '🇨🇦'),
  capeVerde('CV', '카보베르데', 'Cape Verde', '🇨🇻'),
  centralAfricanRepublic('CF', '중앙아프리카공화국', 'Central African Republic', '🇨🇫'),
  chad('TD', '차드', 'Chad', '🇹🇩'),
  chile('CL', '칠레', 'Chile', '🇨🇱'),
  china('CN', '중국', 'China', '🇨🇳'),
  colombia('CO', '콜롬비아', 'Colombia', '🇨🇴'),
  congoDRC('CD', '콩고민주공화국', 'Congo (DRC)', '🇨🇩'),
  costaRica('CR', '코스타리카', 'Costa Rica', '🇨🇷'),
  croatia('HR', '크로아티아', 'Croatia', '🇭🇷'),
  cuba('CU', '쿠바', 'Cuba', '🇨🇺'),
  cyprus('CY', '키프로스', 'Cyprus', '🇨🇾'),
  czechRepublic('CZ', '체코', 'Czech Republic', '🇨🇿'),
  denmark('DK', '덴마크', 'Denmark', '🇩🇰'),
  djibouti('DJ', '지부티', 'Djibouti', '🇩🇯'),
  dominica('DM', '도미니카', 'Dominica', '🇩🇲'),
  dominicanRepublic('DO', '도미니카공화국', 'Dominican Republic', '🇩🇴'),
  ecuador('EC', '에콰도르', 'Ecuador', '🇪🇨'),
  egypt('EG', '이집트', 'Egypt', '🇪🇬'),
  elSalvador('SV', '엘살바도르', 'El Salvador', '🇸🇻'),
  equatorialGuinea('GQ', '적도 기니', 'Equatorial Guinea', '🇬🇶'),
  eritrea('ER', '에리트레아', 'Eritrea', '🇪🇷'),
  estonia('EE', '에스토니아', 'Estonia', '🇪🇪'),
  eswatini('SZ', '에스와티니', 'Eswatini', '🇸🇿'),
  ethiopia('ET', '에티오피아', 'Ethiopia', '🇪🇹'),
  fiji('FJ', '피지', 'Fiji', '🇫🇯'),
  finland('FI', '핀란드', 'Finland', '🇫🇮'),
  france('FR', '프랑스', 'France', '🇫🇷'),
  gabon('GA', '가봉', 'Gabon', '🇬🇦'),
  gambia('GM', '감비아', 'Gambia', '🇬🇲'),
  georgia('GE', '조지아', 'Georgia', '🇬🇪'),
  germany('DE', '독일', 'Germany', '🇩🇪'),
  ghana('GH', '가나', 'Ghana', '🇬🇭'),
  greece('GR', '그리스', 'Greece', '🇬🇷'),
  grenada('GD', '그레나다', 'Grenada', '🇬🇩'),
  guatemala('GT', '과테말라', 'Guatemala', '🇬🇹'),
  guinea('GN', '기니', 'Guinea', '🇬🇳'),
  guineaBissau('GW', '기니비사우', 'Guinea-Bissau', '🇬🇼'),
  guyana('GY', '가이아나', 'Guyana', '🇬🇾'),
  haiti('HT', '아이티', 'Haiti', '🇭🇹'),
  honduras('HN', '온두라스', 'Honduras', '🇭🇳'),
  hongKong('HK', '홍콩', 'Hong Kong', '🇭🇰'),
  hungary('HU', '헝가리', 'Hungary', '🇭🇺'),
  iceland('IS', '아이슬란드', 'Iceland', '🇮🇸'),
  india('IN', '인도', 'India', '🇮🇳'),
  indonesia('ID', '인도네시아', 'Indonesia', '🇮🇩'),
  iran('IR', '이란', 'Iran', '🇮🇷'),
  iraq('IQ', '이라크', 'Iraq', '🇮🇶'),
  ireland('IE', '아일랜드', 'Ireland', '🇮🇪'),
  israel('IL', '이스라엘', 'Israel', '🇮🇱'),
  italy('IT', '이탈리아', 'Italy', '🇮🇹'),
  jamaica('JM', '자메이카', 'Jamaica', '🇯🇲'),
  japan('JP', '일본', 'Japan', '🇯🇵'),
  jordan('JO', '요르단', 'Jordan', '🇯🇴'),
  kazakhstan('KZ', '카자흐스탄', 'Kazakhstan', '🇰🇿'),
  kenya('KE', '케냐', 'Kenya', '🇰🇪'),
  kiribati('KI', '키리바시', 'Kiribati', '🇰🇮'),
  kuwait('KW', '쿠웨이트', 'Kuwait', '🇰🇼'),
  kyrgyzstan('KG', '키르기스스탄', 'Kyrgyzstan', '🇰🇬'),
  laos('LA', '라오스', 'Laos', '🇱🇦'),
  latvia('LV', '라트비아', 'Latvia', '🇱🇻'),
  lebanon('LB', '레바논', 'Lebanon', '🇱🇧'),
  lesotho('LS', '레소토', 'Lesotho', '🇱🇸'),
  liberia('LR', '라이베리아', 'Liberia', '🇱🇷'),
  libya('LY', '리비아', 'Libya', '🇱🇾'),
  liechtenstein('LI', '리히텐슈타인', 'Liechtenstein', '🇱🇮'),
  lithuania('LT', '리투아니아', 'Lithuania', '🇱🇹'),
  luxembourg('LU', '룩셈부르크', 'Luxembourg', '🇱🇺'),
  madagascar('MG', '마다가스카르', 'Madagascar', '🇲🇬'),
  malawi('MW', '말라위', 'Malawi', '🇲🇼'),
  malaysia('MY', '말레이시아', 'Malaysia', '🇲🇾'),
  maldives('MV', '몰디브', 'Maldives', '🇲🇻'),
  mali('ML', '말리', 'Mali', '🇲🇱'),
  malta('MT', '몰타', 'Malta', '🇲🇹'),
  marshallIslands('MH', '마셜 제도', 'Marshall Islands', '🇲🇭'),
  mauritania('MR', '모리타니', 'Mauritania', '🇲🇷'),
  mauritius('MU', '모리셔스', 'Mauritius', '🇲🇺'),
  mexico('MX', '멕시코', 'Mexico', '🇲🇽'),
  micronesia('FM', '미크로네시아', 'Micronesia', '🇫🇲'),
  moldova('MD', '몰도바', 'Moldova', '🇲🇩'),
  monaco('MC', '모나코', 'Monaco', '🇲🇨'),
  mongolia('MN', '몽골', 'Mongolia', '🇲🇳'),
  montenegro('ME', '몬테네그로', 'Montenegro', '🇲🇪'),
  morocco('MA', '모로코', 'Morocco', '🇲🇦'),
  mozambique('MZ', '모잠비크', 'Mozambique', '🇲🇿'),
  myanmar('MM', '미얀마', 'Myanmar', '🇲🇲'),
  namibia('NA', '나미비아', 'Namibia', '🇳🇦'),
  nauru('NR', '나우루', 'Nauru', '🇳🇷'),
  nepal('NP', '네팔', 'Nepal', '🇳🇵'),
  netherlands('NL', '네덜란드', 'Netherlands', '🇳🇱'),
  newZealand('NZ', '뉴질랜드', 'New Zealand', '🇳🇿'),
  nicaragua('NI', '니카라과', 'Nicaragua', '🇳🇮'),
  niger('NE', '니제르', 'Niger', '🇳🇪'),
  nigeria('NG', '나이지리아', 'Nigeria', '🇳🇬'),
  northKorea('KP', '북한', 'North Korea', '🇰🇵'),
  northMacedonia('MK', '북마케도니아', 'North Macedonia', '🇲🇰'),
  norway('NO', '노르웨이', 'Norway', '🇳🇴'),
  oman('OM', '오만', 'Oman', '🇴🇲'),
  pakistan('PK', '파키스탄', 'Pakistan', '🇵🇰'),
  palau('PW', '팔라우', 'Palau', '🇵🇼'),
  palestine('PS', '팔레스타인', 'Palestine', '🇵🇸'),
  panama('PA', '파나마', 'Panama', '🇵🇦'),
  papuaNewGuinea('PG', '파푸아뉴기니', 'Papua New Guinea', '🇵🇬'),
  paraguay('PY', '파라과이', 'Paraguay', '🇵🇾'),
  peru('PE', '페루', 'Peru', '🇵🇪'),
  philippines('PH', '필리핀', 'Philippines', '🇵🇭'),
  poland('PL', '폴란드', 'Poland', '🇵🇱'),
  portugal('PT', '포르투갈', 'Portugal', '🇵🇹'),
  qatar('QA', '카타르', 'Qatar', '🇶🇦'),
  romania('RO', '루마니아', 'Romania', '🇷🇴'),
  russia('RU', '러시아', 'Russia', '🇷🇺'),
  rwanda('RW', '르완다', 'Rwanda', '🇷🇼'),
  saintKittsAndNevis('KN', '세인트키츠 네비스', 'Saint Kitts and Nevis', '🇰🇳'),
  saintLucia('LC', '세인트루시아', 'Saint Lucia', '🇱🇨'),
  saintVincentAndTheGrenadines('VC', '세인트빈센트 그레나딘', 'Saint Vincent and the Grenadines', '🇻🇨'),
  samoa('WS', '사모아', 'Samoa', '🇼🇸'),
  sanMarino('SM', '산마리노', 'San Marino', '🇸🇲'),
  saoTomeAndPrincipe('ST', '상투메 프린시페', 'Sao Tome and Principe', '🇸🇹'),
  saudiArabia('SA', '사우디아라비아', 'Saudi Arabia', '🇸🇦'),
  senegal('SN', '세네갈', 'Senegal', '🇸🇳'),
  serbia('RS', '세르비아', 'Serbia', '🇷🇸'),
  seychelles('SC', '세이셸', 'Seychelles', '🇸🇨'),
  sierraLeone('SL', '시에라리온', 'Sierra Leone', '🇸🇱'),
  singapore('SG', '싱가포르', 'Singapore', '🇸🇬'),
  slovakia('SK', '슬로바키아', 'Slovakia', '🇸🇰'),
  slovenia('SI', '슬로베니아', 'Slovenia', '🇸🇮'),
  solomonIslands('SB', '솔로몬 제도', 'Solomon Islands', '🇸🇧'),
  somalia('SO', '소말리아', 'Somalia', '🇸🇴'),
  southAfrica('ZA', '남아프리카공화국', 'South Africa', '🇿🇦'),
  southKorea('KR', '대한민국', 'South Korea', '🇰🇷'),
  southSudan('SS', '남수단', 'South Sudan', '🇸🇸'),
  spain('ES', '스페인', 'Spain', '🇪🇸'),
  sriLanka('LK', '스리랑카', 'Sri Lanka', '🇱🇰'),
  sudan('SD', '수단', 'Sudan', '🇸🇩'),
  suriname('SR', '수리남', 'Suriname', '🇸🇷'),
  sweden('SE', '스웨덴', 'Sweden', '🇸🇪'),
  switzerland('CH', '스위스', 'Switzerland', '🇨🇭'),
  syria('SY', '시리아', 'Syria', '🇸🇾'),
  taiwan('TW', '대만', 'Taiwan', '🇹🇼'),
  tajikistan('TJ', '타지키스탄', 'Tajikistan', '🇹🇯'),
  tanzania('TZ', '탄자니아', 'Tanzania', '🇹🇿'),
  thailand('TH', '태국', 'Thailand', '🇹🇭'),
  timorLeste('TL', '동티모르', 'Timor-Leste', '🇹🇱'),
  togo('TG', '토고', 'Togo', '🇹🇬'),
  tonga('TO', '통가', 'Tonga', '🇹🇴'),
  trinidadAndTobago('TT', '트리니다드 토바고', 'Trinidad and Tobago', '🇹🇹'),
  tunisia('TN', '튀니지', 'Tunisia', '🇹🇳'),
  turkey('TR', '튀르키예', 'Turkey', '🇹🇷'),
  turkmenistan('TM', '투르크메니스탄', 'Turkmenistan', '🇹🇲'),
  tuvalu('TV', '투발루', 'Tuvalu', '🇹🇻'),
  uganda('UG', '우간다', 'Uganda', '🇺🇬'),
  ukraine('UA', '우크라이나', 'Ukraine', '🇺🇦'),
  unitedArabEmirates('AE', '아랍에미리트', 'United Arab Emirates', '🇦🇪'),
  unitedKingdom('GB', '영국', 'United Kingdom', '🇬🇧'),
  unitedStates('US', '미국', 'United States', '🇺🇸'),
  uruguay('UY', '우루과이', 'Uruguay', '🇺🇾'),
  uzbekistan('UZ', '우즈베키스탄', 'Uzbekistan', '🇺🇿'),
  vanuatu('VU', '바누아투', 'Vanuatu', '🇻🇺'),
  vaticanCity('VA', '바티칸', 'Vatican City', '🇻🇦'),
  venezuela('VE', '베네수엘라', 'Venezuela', '🇻🇪'),
  vietnam('VN', '베트남', 'Vietnam', '🇻🇳'),
  yemen('YE', '예멘', 'Yemen', '🇾🇪'),
  zambia('ZM', '잠비아', 'Zambia', '🇿🇲'),
  zimbabwe('ZW', '짐바브웨', 'Zimbabwe', '🇿🇼');

  const Country(this.code, this.name, this.nameEn, this.flag);

  final String code;
  final String name;
  final String nameEn;
  final String flag;

  /// 국가 코드로 국가 찾기
  static Country? fromCode(String code) {
    try {
      return Country.values.firstWhere((country) => country.code == code);
    } catch (e) {
      return null;
    }
  }

  /// 국가 검색 (한글, 영문 모두 지원)
  static List<Country> search(String query) {
    if (query.isEmpty) return Country.values;

    final lowerQuery = query.toLowerCase();
    return Country.values.where((country) {
      final name = country.name.toLowerCase();
      final nameEn = country.nameEn.toLowerCase();
      return name.contains(lowerQuery) || nameEn.contains(lowerQuery);
    }).toList();
  }
}
